name: Go Continuous Integration

on:
  push:
    branches: [ develop ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Installing Depedencies
      run: |
        go get -u golang.org/x/lint/golint
        go mod download

    - name: Go Format and Linting
      run: |
        golint ./...
        go fmt ./...

    - name: Go Testing
      run: |
        go test -v ./...
