name: Go Continuous Integration

on:
  push:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Installing Depedencies
      run: go mod download

    - name: Go Format and Linting
      run: go fmt ./...

    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        mysql version: '8.0'
        mysql database: 'go-service'
        mysql root password: 'root_password'
        mysql user: 'root'
        mysql password: 'password'

    - name: Go Testing
      run: go test -v ./...
